version: "3"

services:
   arj-db:
     container_name: bookclub-db
     build:
       context: ./
       dockerfile: ./mysql/Dockerfile
     ports: 
       - "3306:3306"
     networks:
       - compose
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: arj_pw
       MYSQL_DATABASE: arj
       MYSQL_USER: arj
       MYSQL_PASSWORD: Password1

volumes: 
  db_data:
    external: false 
networks: 
  compose: 
    name: bookclub-compose
