// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/Action-for-Racial-Justice/bookclub-backend/internal/config"
	"github.com/Action-for-Racial-Justice/bookclub-backend/internal/handlers"
	"github.com/Action-for-Racial-Justice/bookclub-backend/internal/server"
	"github.com/Action-for-Racial-Justice/bookclub-backend/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeAndRun(ctx context.Context, cfg config.FilePath) (*server.Server, func(), error) {
	configConfig := config.NewConfig(cfg)
	serverConfig := config.NewServerConfig(configConfig)
	bookClubService := service.New()
	bookClubHandler, err := handlers.New(bookClubService)
	if err != nil {
		return nil, nil, err
	}
	serverServer, cleanup, err := server.New(ctx, serverConfig, bookClubHandler)
	if err != nil {
		return nil, nil, err
	}
	return serverServer, func() {
		cleanup()
	}, nil
}

// wire.go:

var serviceModule = wire.NewSet(service.Module, wire.Bind(new(service.Service), new(*service.BookClubService)))

var handlersModule = wire.NewSet(handlers.Module, wire.Bind(new(handlers.Handlers), new(*handlers.BookClubHandler)))
