CREATE TABLE IF NOT EXISTS user (
  id VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  clubAssigned tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS session (
  entryID VARCHAR(255) NOT NULL,
  userID VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL,
  CONSTRAINT s_fk_1 FOREIGN KEY (userID) REFERENCES user (id),
  PRIMARY KEY (entryID)
);

CREATE TABLE IF NOT EXISTS book (
  entryID VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  isActive boolean,
  PRIMARY KEY (entryID)
);


CREATE TABLE IF NOT EXISTS club (
  entryID VARCHAR(255) NOT NULL,
  leaderID VARCHAR(255) NOT NULL,
  clubName VARCHAR(255) NOT NULL,
  bookID VARCHAR(255),
  description VARCHAR(1000) NOT NULL,
  CONSTRAINT c_fk_1 FOREIGN KEY (leaderID) REFERENCES user (id),
  CONSTRAINT c_fk_2 FOREIGN KEY (bookID) REFERENCES book (entryID),
  PRIMARY KEY (entryID),
  UNIQUE INDEX clubName_UNIQUE (clubName ASC)
);


CREATE TABLE IF NOT EXISTS club_member (
  entryID VARCHAR(255) NOT NULL,
  userID VARCHAR(255) NOT NULL,
  clubID VARCHAR(255) NOT NULL,
  CONSTRAINT cm_fk_1 FOREIGN KEY (userID) REFERENCES user (id),
  CONSTRAINT cm_fk_2 FOREIGN KEY (clubID) REFERENCES club (entryID),
  PRIMARY KEY (entryID)
);